import json
from pathlib import Path
from forge.src.forge.application.ports.project_generator import ProjectGenerator
from forge.src.forge.domain.project import Project
from forge.src.forge.infrastructure.generators.base_generator import BaseGenerator


class NodeProjectGenerator(BaseGenerator, ProjectGenerator):
    """
        Professional Node.js project generator
        - Always uses TypeScript
        - Supports Express or Fastify
        - Includes ESLint, Prettier, Jest
        - Production‑ready scaffold similar to create-next-app quality
    """
    def __init__(self, base_path: str = ".", framework: str = "express"):
        super().__init__(base_path)
        self.framework = framework.lower()
        
        if self.framework not in {"express", "fastify"}:
            raise ValueError("Framework must be 'express' or 'fastify'")
        
    # =========================================================
    # PUBLIC API
    # =========================================================
    
    def generate(self, project: Project):
        root = self.base_path / project.name
        
        self.create_dir(root / "src")
        self.create_dir(root / "tests")
        
                # core files
        self._create_package_json(root, project)
        self._create_tsconfig(root)
        self._create_eslint(root)
        self._create_prettier(root)
        self._create_jest(root)
        self._create_entrypoint(root)
        self._create_gitignore(root)
        self._create_readme(root, project)
     
    # =========================================================
    # PACKAGE.JSON
    # =========================================================

    def _create_package_json(self, root: Path, project: Project):
        dependencies = {}

        if self.framework == "express":
            dependencies["express"] = "^4.19.0"
        else:
            dependencies["fastify"] = "^4.0.0"

        dev_dependencies = {
            "typescript": "^5.0.0",
            "tsx": "^4.0.0",
            "@types/node": "^20.0.0",
            "eslint": "^9.0.0",
            "@typescript-eslint/parser": "^7.0.0",
            "@typescript-eslint/eslint-plugin": "^7.0.0",
            "prettier": "^3.0.0",
            "jest": "^29.0.0",
            "ts-jest": "^29.0.0",
            "@types/jest": "^29.0.0",
        }

        package = {
            "name": project.name,
            "version": "1.0.0",
            "description": "Generated by Forge CLI",
            "license": "MIT",
            "type": "module",
            "main": "dist/index.js",
            "scripts": {
                "dev": "tsx watch src/index.ts",
                "build": "tsc",
                "start": "node dist/index.js",
                "lint": "eslint .",
                "format": "prettier --write .",
                "test": "jest",
            },
            "dependencies": dependencies,
            "devDependencies": dev_dependencies,
        }

        self.write_file(root / "package.json", json.dumps(package, indent=2))


    # =========================================================
    # TYPESCRIPT
    # =========================================================

    def _create_tsconfig(self, root: Path):
        tsconfig = {
            "compilerOptions": {
                "target": "ES2020",
                "module": "ESNext",
                "moduleResolution": "Node",
                "outDir": "dist",
                "rootDir": "src",
                "strict": True,
                "esModuleInterop": True,
                "skipLibCheck": True,
            }
        }

        self.write_file(root / "tsconfig.json", json.dumps(tsconfig, indent=2))

    # =========================================================
    # ESLINT
    # =========================================================

    def _create_eslint(self, root: Path):
        eslint = {
            "parser": "@typescript-eslint/parser",
            "plugins": ["@typescript-eslint"],
            "extends": [
                "eslint:recommended",
                "plugin:@typescript-eslint/recommended",
                "prettier",
            ],
            "env": {"node": True, "jest": True},
        }

        self.write_file(root / ".eslintrc.json", json.dumps(eslint, indent=2))

    # =========================================================
    # PRETTIER
    # =========================================================

    def _create_prettier(self, root: Path):
        prettier = {
            "semi": True,
            "singleQuote": False,
            "trailingComma": "all",
            "printWidth": 80,
        }

        self.write_file(root / ".prettierrc", json.dumps(prettier, indent=2))


    # =========================================================
    # JEST
    # =========================================================

    def _create_jest(self, root: Path):
        jest = {
            "preset": "ts-jest",
            "testEnvironment": "node",
            "roots": ["<rootDir>/tests"],
        }

        self.write_file(root / "jest.config.json", json.dumps(jest, indent=2))

    # =========================================================
    # ENTRYPOINT
    # =========================================================

    def _create_entrypoint(self, root: Path):
        if self.framework == "express":
            content = '''
                import express from "express";

                const app = express();

                app.get("/", (_req, res) => {
                res.json({ message: "Hello from Express + TypeScript 🚀" });
                });

                app.listen(3000, () => {
                console.log("Server running on http://localhost:3000");
                });
                '''
        else:
            content = '''
                import Fastify from "fastify";

                const app = Fastify();

                app.get("/", async () => {
                return { message: "Hello from Fastify + TypeScript 🚀" };
                });

                app.listen({ port: 3000 }, () => {
                console.log("Server running on http://localhost:3000");
                });
                '''

        self.write_file(root / "src" / "index.ts", content.strip())

    # =========================================================
    # OTHER FILES
    # =========================================================

    def _create_gitignore(self, root: Path):
        content = """
            node_modules
            dist
            .env
            coverage
        """
        self.write_file(root / ".gitignore", content.strip())

    def _create_readme(self, root: Path, project: Project):
        content = f"""
            # {project.name}

            Project generated with **Forge CLI**.

            ## Scripts

            - npm run dev → development
            - npm run build → compile TypeScript
            - npm start → run production build
            - npm test → run Jest

            ## Stack

            - Node.js
            - TypeScript
            - {self.framework.title()}
            - ESLint + Prettier
            - Jest
            """
        self.write_file(root / "README.md", content.strip())
